In [1]:
import os
from scipy.io.wavfile import read
import numpy as np
import librosa
import matplotlib.pyplot as plt
import soundfile as sf


In [2]:
ex = sf.read('Pure Noise/air_conditioner/101729.wav')
ex[0].shape[0]

4059841

In [3]:

if (ex[0].shape[1]==2):
        d = (np.sum(ex[0], axis=1))/2

print(ex)
print(d)

(array([[ 0.01465309,  0.01465321],
       [ 0.01815999,  0.01815999],
       [ 0.02058482,  0.02058482],
       ..., 
       [-0.00668955, -0.00668955],
       [-0.01221633, -0.01221633],
       [-0.00820029, -0.00820029]]), 48000)
[ 0.01465315  0.01815999  0.02058482 ..., -0.00668955 -0.01221633
 -0.00820029]


In [4]:
noise_types = os.listdir('Pure Noise/')

In [ ]:
noise_types

['.DS_Store', 'air_conditioner', 'Bike', 'car', 'plane', 'Train']

In [ ]:
data = []
labels = []
for nt in noise_types[1:]:
    all_files = os.listdir('Pure Noise/' + nt + '/')
    for file in all_files:
        if file.endswith('.wav'):
            print('Loading: ' + 'Pure Noise/' + nt + '/' + file)
            wav_data = sf.read('Pure Noise/' + nt + '/' + file)
            print(wav_data)
            d = wav_data[0]
            if (len(wav_data[0].shape) == 2):
                d = (np.sum(wav_data[0], axis=1))/2
            data.append(d.tolist())
            labels.append(nt)
            print(len(data))
            print(len(labels))
            
labels = np.array(labels)
data = np.array(data)

Loading: Pure Noise/air_conditioner/101729.wav
(array([[ 0.01465309,  0.01465321],
       [ 0.01815999,  0.01815999],
       [ 0.02058482,  0.02058482],
       ..., 
       [-0.00668955, -0.00668955],
       [-0.01221633, -0.01221633],
       [-0.00820029, -0.00820029]]), 48000)
1
1
Loading: Pure Noise/air_conditioner/121285.wav
(array([[ 0.02655029,  0.09140015],
       [ 0.05767822,  0.11486816],
       [ 0.08782959,  0.14907837],
       ..., 
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]]), 48000)
2
2
Loading: Pure Noise/air_conditioner/121286.wav
(array([[  0.00000000e+00,   0.00000000e+00],
       [ -9.15527344e-05,   4.27246094e-04],
       [ -3.35693359e-04,   8.85009766e-04],
       ..., 
       [  0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00]]), 48000)
3
3
Loading: Pure Noise/air_conditioner/127872.wav
(array([ 0.00206184,  0.00769818,  0.0141

(array([ 0.00405884,  0.00482178,  0.00512695, ..., -0.00259399,
       -0.00268555, -0.00219727]), 44100)
29
29
Loading: Pure Noise/air_conditioner/56385.wav
(array([[ 0.02252197,  0.05062866],
       [ 0.01950073,  0.04425049],
       [ 0.01522827,  0.03445435],
       ..., 
       [ 0.01748657,  0.03387451],
       [ 0.02084351,  0.03585815],
       [ 0.02365112,  0.03637695]]), 44100)
30
30
Loading: Pure Noise/air_conditioner/57320.wav
(array([[  0.00000000e+00,   0.00000000e+00],
       [ -3.05175781e-05,   3.05175781e-05],
       [  0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.05175781e-05],
       [  3.05175781e-05,   0.00000000e+00]]), 44100)
31
31
Loading: Pure Noise/air_conditioner/60846.wav
(array([[ 0.08325195,  0.07507324],
       [ 0.0866394 ,  0.0736084 ],
       [ 0.08816528,  0.07452393],
       ..., 
       [ 0.04205322,  0.06103516],
       [ 0.04724121,  0.05932617],
       [ 0.05459595,  

In [ ]:
data.shape

In [ ]:
data